#!/usr/bin/env python3
"""Utility for generating marketing file headers for PlantUML files."""

from __future__ import annotations

import os
from pathlib import Path


DEFAULT_HEADER = """Generated by uml-gen | View: vscode-umlmark | Eclipse: UMLMark | © Peppermint
(https://github.com/petercai)"""


def read_mark_file(script_path: Path) -> str:
    """Read mark.txt from the package directory, or return default.
    
    Args:
        script_path: Path to the script file (e.g., __file__)
    
    Returns:
        Content to use as file header (without comment markers).
    """
    script_dir = Path(script_path).parent
    mark_file = script_dir / "mark.txt"

    if mark_file.exists():
        try:
            content = mark_file.read_text(encoding="utf-8").strip()
            if content:
                return content
        except Exception:
            return DEFAULT_HEADER
    
    return DEFAULT_HEADER


def prepend_plantuml_header(content: str, header_text: str) -> str:
    """Insert a marketing header to PlantUML content after @startuml directive.
    
    The header is inserted as a multi-line comment block right after @startuml line.
    
    Args:
        content: The PlantUML diagram content
        header_text: The header text to insert (multiple lines OK)
    
    Returns:
        PlantUML content with header inserted after @startuml.
    """
    if not header_text.strip():
        return content
    
    # Find the @startuml line
    lines = content.split("\n")
    startuml_idx = -1
    for idx, line in enumerate(lines):
        if line.strip().startswith("@startuml"):
            startuml_idx = idx
            break
    
    if startuml_idx == -1:
        # No @startuml found, just return original content
        return content
    
    # Format header as PlantUML comment block (no leading/trailing empty lines)
    header_lines = header_text.strip().split("\n")
    comment_block = [f"' {line}" for line in header_lines]
    
    # Remove existing metadata comment lines (Generated by, Depth, etc.)
    # that immediately follow @startuml
    existing_idx = startuml_idx + 1
    while existing_idx < len(lines):
        stripped = lines[existing_idx].strip()
        # Check if this is an old metadata line
        if stripped.startswith("'") and (
            "Generated by" in stripped or "Depth:" in stripped
        ):
            existing_idx += 1
        else:
            break
    
    # Insert header after @startuml line, removing old metadata lines
    result_lines = lines[:startuml_idx + 1] + comment_block + lines[existing_idx:]
    return "\n".join(result_lines)
